title: Adapt Applications Documentation
description: Documentation for the Adapt Apps System.
theme: just-the-docs

url: https://adaptapplications.github.io/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"